### PR TITLE
Staging0

### PR DESCRIPTION
**Pull request by johnraff**
The user bunsen/autostart file has been split into autostart and autostart-wayland for better insulation of the two systems from each other, and to keep them as free as possible of shell code for user comfort. bunsenlabs-session and bunsen-autostart have been adjusted to choose the correct file depending on what session is being launched.

### CODE REVIEW

**Comment by 01micko** [comment]
@johnraff  I'm happy to merge verbatim and we can add stuff later :)

Thoughts?

**Comment by johnraff** [comment]
I don't think I've done anything too drastic - the biggest change is splitting the two user autostarts, and (empty) environment files. If you're OK with merging in that PR as it is for now, there's certainly plenty of scope for improving things down the road, by one or the other of us.

It's tested out OK on my VM with your recent netinstall install. I haven't yet checked on an X11 system but think it should be OK.

**Comment by 01micko** [comment]
Ok, going to merge.

**Comment by johnraff** [comment]
Sorry I let a small bug in.
In bunsen-autostart line 13:
https://github.com/01micko/bunsen-configs/blob/4a94a358f2e9a44aaa7782540e3162a41599f5af/bunsen-autostart#L13
the `-x` was for debugging and can be removed. It does no real harm at this stage, but could you maybe take it out?

**Comment by johnraff** [comment]
Sorry I let a couple of bugs in.
In bunsen-autostart line 13:
https://github.com/01micko/bunsen-configs/blob/4a94a358f2e9a44aaa7782540e3162a41599f5af/bunsen-autostart#L13
the `-x` was for debugging and can be removed. It does no real harm at this stage, but could you maybe take it out?

Another thing we'll need to look at:
https://github.com/01micko/bunsen-configs/blob/4a94a358f2e9a44aaa7782540e3162a41599f5af/skel-wbase/skel/.config/bunsen/autostart#L82
policykit-1-gnome will no longer be available for X11 in Trixie, so that section will need to be changed. I provisionally tried out lxpolkit but there are a couple of alternatives to consider: https://packages.debian.org/trixie/polkit-1-auth-agent
Sorry I left  that a bit messy - I'm still not 100% sure what we want to use there.

**Comment by 01micko** [comment]
It's ok. This isn't a stable branch so we can sort it out.

**Comment by johnraff** [comment]
I sketched out a framework how the packages might fit together:
https://forums.bunsenlabs.org/viewtopic.php?id=9081

**Pull request merged**
